-- Day 5: store plans as a template (phases → days → items).
-- Written to run on both H2 (local dev, PostgreSQL mode) and PostgreSQL.
-- Text columns are VARCHAR so Hibernate's schema validation matches on both databases.

CREATE TABLE plans (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(500)    NOT NULL,
    category      VARCHAR(30)     NOT NULL,
    weeks         INTEGER         NOT NULL,
    start_date    DATE            NOT NULL,
    day_offset    INTEGER         NOT NULL DEFAULT 0,  -- used by "Shift plan" (Day 13)
    raw_markdown  VARCHAR(100000) NOT NULL,            -- kept so old plans can be re-parsed later
    created_at    TIMESTAMP       NOT NULL
);

CREATE TABLE plan_phases (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id    BIGINT       NOT NULL REFERENCES plans (id) ON DELETE CASCADE,
    from_week  INTEGER      NOT NULL,
    to_week    INTEGER      NOT NULL,
    name       VARCHAR(500) NOT NULL
);
CREATE INDEX idx_plan_phases_plan ON plan_phases (plan_id);

CREATE TABLE plan_days (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id    BIGINT       NOT NULL REFERENCES plan_phases (id) ON DELETE CASCADE,
    weekday     VARCHAR(9)   NOT NULL,   -- MONDAY ... SUNDAY
    title       VARCHAR(500) NOT NULL,
    sort_order  INTEGER      NOT NULL
);
CREATE INDEX idx_plan_days_phase ON plan_days (phase_id);

CREATE TABLE plan_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_id        BIGINT       NOT NULL REFERENCES plan_days (id) ON DELETE CASCADE,
    sort_order    INTEGER      NOT NULL,
    name          VARCHAR(500) NOT NULL,
    set_count     INTEGER      NOT NULL,
    reps_kind     VARCHAR(10)  NOT NULL,  -- COUNT, SECONDS, MAX, TEXT
    reps_value    INTEGER,                -- null for MAX and TEXT
    reps_detail   VARCHAR(500) NOT NULL,
    reps_raw      VARCHAR(500) NOT NULL,
    rest_seconds  INTEGER,
    note          VARCHAR(500) NOT NULL
);
CREATE INDEX idx_plan_items_day ON plan_items (day_id);
