-- Day 7: a row means "this exercise was done on this date". Unticking deletes the row.
CREATE TABLE completions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT    NOT NULL REFERENCES plans (id) ON DELETE CASCADE,
    item_id     BIGINT    NOT NULL REFERENCES plan_items (id) ON DELETE CASCADE,
    done_on     DATE      NOT NULL,          -- calendar date the user did it
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_completion_item_day UNIQUE (item_id, done_on)
);
CREATE INDEX idx_completions_plan_day ON completions (plan_id, done_on);
