-- Day 13: "I missed it, move on." A skipped day is left out of progress
-- and doesn't break the streak. Unskipping deletes the row.
CREATE TABLE skipped_days (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT    NOT NULL REFERENCES plans (id) ON DELETE CASCADE,
    skip_on     DATE      NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_skip_plan_day UNIQUE (plan_id, skip_on)
);
CREATE INDEX idx_skipped_days_plan ON skipped_days (plan_id, skip_on);
