-- Day 21: a rest day is part of the plan, not a gap in it. Ticking one off
-- records that you took it on purpose. Untapping deletes the row.
CREATE TABLE rested_days (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT    NOT NULL REFERENCES plans (id) ON DELETE CASCADE,
    rested_on   DATE      NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_rest_plan_day UNIQUE (plan_id, rested_on)
);
CREATE INDEX idx_rested_days_plan ON rested_days (plan_id, rested_on);
